name: Auto Sync Fork

on:
  schedule:
    - cron: '*/30 0 * * *'
  workflow_dispatch:     # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync main branch
        run: |
          git fetch https://github.com/router-for-me/CLIProxyAPIPlus.git main
          git checkout main
          git reset --hard FETCH_HEAD
          git push origin main --force
